#Dockerfile based on the latest Centos 7 imae - non-privileged user entry
FROM centos:latest
MAINTAINER sam943@gmail.com

RUN useradd -ms /bin/bash user

User user

ENTRYPOINT echo "This command will display this message on EVERY container"
